BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Shitposts` (
	`seq_id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`snowflake`	INTEGER,
	`username`	TEXT,
	`shitpost`	TEXT,
	`fullmessage`	TEXT,
	`date`	INTEGER
);
CREATE TABLE IF NOT EXISTS `Servers` (
	`name`	TEXT,
	`description`	TEXT,
	`address`	TEXT,
	`rcon_password`	TEXT,
	`ftp_path`	TEXT,
	`ftp_username`	TEXT,
	`ftp_password`	TEXT,
	`ftp_type`	TEXT,
	PRIMARY KEY(`name`)
);
CREATE TABLE IF NOT EXISTS `SearchDataTags` (
	`name`	TEXT,
	`tag`	TEXT,
	`series`	TEXT,
	PRIMARY KEY(`name`,`tag`,`series`)
);
INSERT INTO `SearchDataTags` VALUES ('v2 1','1','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 1','installing','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 1','configuration','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 2','2','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 2','sky','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 2','skybox','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 3','3','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 3','clipping','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 3','brush','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 4','4','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 4','leak','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 4','leaks','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 4','lin','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 5','5','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 5','prop','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 5','static','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 5','prop_static','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 5','prop_dynamic','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 6','6','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 6','optimization','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 6','pvs','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 6','prt','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 6','func_detail','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 7','7','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 7','vertex','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 7','primitive','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 8','8','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 8','light','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 8','lighting','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 8','point_spotlight','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 8','light_spot','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 8','env_sprite','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 8','hdr','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 8','rad','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 8','smoothing','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 8','projectedtexture','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 9','9','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 9','displacement','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 9','sew','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 10','10','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 10','water','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 11','11','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 11','door','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 11','prop_door','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 11','func_door','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 12','12','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 12','intput','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 12','output','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 12','io','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 13','13','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 13','vmt','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 13','normal','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 13','vtf','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 13','packing','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 13','pack','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 13','vide','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 13','texture','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 14','14','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 14','cubemap','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 14','envmap','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 14','specmask','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 15','15','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 15','skybox','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 15','sky_camera','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 16','16','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 16','fog','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 16','env_fog_controller','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 17','17','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 17','color','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 17','correction','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 17','raw','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 18','18','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 18','movelinear','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 19','19','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 19','parent','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 19','parenting','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 19','attachment','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 20','20','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 20','rotating','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 20','func_rotating','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 20','fan','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 21','21','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 21','optimization','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 21','func_detail','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 21','hint','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 21','skip','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 21','areaportal','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 22','22','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 22','sound','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 22','soundscape','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 22','ambient_generic','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 22','script','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 23','23','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 23','texture','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 23','alignement','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 23','justify','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 23','wrap','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 24','24','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 24','decal','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 24','overlay','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 24','dekale','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 25','25','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 25','radar','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 25','overview','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 25','hostage','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 25','bomb','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 26','26','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 26','blendmodulate','v2');
INSERT INTO `SearchDataTags` VALUES ('v2 26','blend','v2');
INSERT INTO `SearchDataTags` VALUES ('bc1','1','bc');
INSERT INTO `SearchDataTags` VALUES ('bc1','installing','bc');
INSERT INTO `SearchDataTags` VALUES ('bc1','understanding','bc');
INSERT INTO `SearchDataTags` VALUES ('bc2','2','bc');
INSERT INTO `SearchDataTags` VALUES ('bc2','room','bc');
INSERT INTO `SearchDataTags` VALUES ('bc2','skybox','bc');
INSERT INTO `SearchDataTags` VALUES ('bc3','3','bc');
INSERT INTO `SearchDataTags` VALUES ('bc3','vertex','bc');
INSERT INTO `SearchDataTags` VALUES ('bc3','shaping','bc');
INSERT INTO `SearchDataTags` VALUES ('bc3','clipping','bc');
INSERT INTO `SearchDataTags` VALUES ('bc4','4','bc');
INSERT INTO `SearchDataTags` VALUES ('bc4','intro','bc');
INSERT INTO `SearchDataTags` VALUES ('bc4','introduction','bc');
INSERT INTO `SearchDataTags` VALUES ('bc4','design','bc');
INSERT INTO `SearchDataTags` VALUES ('bc4','layout','bc');
INSERT INTO `SearchDataTags` VALUES ('bc5','5','bc');
INSERT INTO `SearchDataTags` VALUES ('bc5','testing','bc');
INSERT INTO `SearchDataTags` VALUES ('bc5','layout','bc');
INSERT INTO `SearchDataTags` VALUES ('bc5','design','bc');
INSERT INTO `SearchDataTags` VALUES ('bc6','6','bc');
INSERT INTO `SearchDataTags` VALUES ('bc6','prop','bc');
INSERT INTO `SearchDataTags` VALUES ('bc6','static','bc');
INSERT INTO `SearchDataTags` VALUES ('bc6','prop_static','bc');
INSERT INTO `SearchDataTags` VALUES ('bc6','prop_dynamic','bc');
INSERT INTO `SearchDataTags` VALUES ('bc6','prop_physics','bc');
INSERT INTO `SearchDataTags` VALUES ('bc7','7','bc');
INSERT INTO `SearchDataTags` VALUES ('bc7','optimization','bc');
INSERT INTO `SearchDataTags` VALUES ('bc7','func_detail','bc');
INSERT INTO `SearchDataTags` VALUES ('bc8','8','bc');
INSERT INTO `SearchDataTags` VALUES ('bc8','mode','bc');
INSERT INTO `SearchDataTags` VALUES ('bc8','radar','bc');
INSERT INTO `SearchDataTags` VALUES ('bc8','overview','bc');
INSERT INTO `SearchDataTags` VALUES ('bc9','9','bc');
INSERT INTO `SearchDataTags` VALUES ('bc9','texture','bc');
INSERT INTO `SearchDataTags` VALUES ('bc9','texturing','bc');
INSERT INTO `SearchDataTags` VALUES ('bc10','10','bc');
INSERT INTO `SearchDataTags` VALUES ('bc10','displacement','bc');
INSERT INTO `SearchDataTags` VALUES ('bc10','displacements','bc');
INSERT INTO `SearchDataTags` VALUES ('bc10','sew','bc');
INSERT INTO `SearchDataTags` VALUES ('bc11','11','bc');
INSERT INTO `SearchDataTags` VALUES ('bc11','lighting','bc');
INSERT INTO `SearchDataTags` VALUES ('bc11','light','bc');
INSERT INTO `SearchDataTags` VALUES ('bc11','light_spot','bc');
INSERT INTO `SearchDataTags` VALUES ('bc12','12','bc');
INSERT INTO `SearchDataTags` VALUES ('bc12','lighting','bc');
INSERT INTO `SearchDataTags` VALUES ('bc12','light','bc');
INSERT INTO `SearchDataTags` VALUES ('bc12','sprite','bc');
INSERT INTO `SearchDataTags` VALUES ('bc12','lightmap','bc');
INSERT INTO `SearchDataTags` VALUES ('bc13','13','bc');
INSERT INTO `SearchDataTags` VALUES ('bc13','lighting','bc');
INSERT INTO `SearchDataTags` VALUES ('bc13','light','bc');
INSERT INTO `SearchDataTags` VALUES ('bc13','hdr','bc');
INSERT INTO `SearchDataTags` VALUES ('bc13','smoothing','bc');
INSERT INTO `SearchDataTags` VALUES ('bc14','14','bc');
INSERT INTO `SearchDataTags` VALUES ('bc14','doors','bc');
INSERT INTO `SearchDataTags` VALUES ('bc14','chicken','bc');
INSERT INTO `SearchDataTags` VALUES ('bc14','ladder','bc');
INSERT INTO `SearchDataTags` VALUES ('bc15','15','bc');
INSERT INTO `SearchDataTags` VALUES ('bc15','skybox','bc');
INSERT INTO `SearchDataTags` VALUES ('bc15','fog','bc');
INSERT INTO `SearchDataTags` VALUES ('bc16','16','bc');
INSERT INTO `SearchDataTags` VALUES ('bc16','texture','bc');
INSERT INTO `SearchDataTags` VALUES ('bc16','cubemap','bc');
INSERT INTO `SearchDataTags` VALUES ('bc16','reflection','bc');
INSERT INTO `SearchDataTags` VALUES ('bc16','envmap','bc');
INSERT INTO `SearchDataTags` VALUES ('bc16','env_cubemap','bc');
INSERT INTO `SearchDataTags` VALUES ('bc17','17','bc');
INSERT INTO `SearchDataTags` VALUES ('bc17','decal','bc');
INSERT INTO `SearchDataTags` VALUES ('bc17','overlay','bc');
INSERT INTO `SearchDataTags` VALUES ('bc17','detail','bc');
INSERT INTO `SearchDataTags` VALUES ('bc18','18','bc');
INSERT INTO `SearchDataTags` VALUES ('bc18','sound','bc');
INSERT INTO `SearchDataTags` VALUES ('bc18','soundscape','bc');
INSERT INTO `SearchDataTags` VALUES ('bc19','19','bc');
INSERT INTO `SearchDataTags` VALUES ('bc19','optimization','bc');
INSERT INTO `SearchDataTags` VALUES ('bc19','hint','bc');
INSERT INTO `SearchDataTags` VALUES ('bc19','skip','bc');
INSERT INTO `SearchDataTags` VALUES ('bc19','areaportal','bc');
INSERT INTO `SearchDataTags` VALUES ('bc20','20','bc');
INSERT INTO `SearchDataTags` VALUES ('bc20','optimization','bc');
INSERT INTO `SearchDataTags` VALUES ('bc20','hint','bc');
INSERT INTO `SearchDataTags` VALUES ('bc20','skip','bc');
INSERT INTO `SearchDataTags` VALUES ('bc20','areaportal','bc');
INSERT INTO `SearchDataTags` VALUES ('bc21','21','bc');
INSERT INTO `SearchDataTags` VALUES ('bc21','publishing','bc');
INSERT INTO `SearchDataTags` VALUES ('bc21','finalizing','bc');
INSERT INTO `SearchDataTags` VALUES ('bc21','upload','bc');
INSERT INTO `SearchDataTags` VALUES ('bc21','finish','bc');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp1','mfp1','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp1','mfp','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp1','first','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp1','prop','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp1','modeling','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp1','3dsmax','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp2','mfp2','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp2','mfp','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp2','texturing','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp2','substance','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp3','mfp3','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp3','mfp','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp3','exporting','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp3','wallworm','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds mfp3','wwmt','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 1','1','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 1','introduction','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 1','3dsmax','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 2','2','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 2','geometry','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 2','primitives','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 3','3','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 3','splines','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 3','spline','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 4','4','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 4','model','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 4','basic','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 4','lamp','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 5','5','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 5','uvw','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds 5','unwrap','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds gen1','wwmt','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds gen1','wallworm','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds gen1','install','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds gen2','export','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds gen2','wwmt','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds gen2','wallworm','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds gen2','prop_static','3ds');
INSERT INTO `SearchDataTags` VALUES ('3ds gen2','static','3ds');
INSERT INTO `SearchDataTags` VALUES ('written1','1','written');
INSERT INTO `SearchDataTags` VALUES ('written1','lighting','written');
INSERT INTO `SearchDataTags` VALUES ('written1','light','written');
INSERT INTO `SearchDataTags` VALUES ('written2','2','written');
INSERT INTO `SearchDataTags` VALUES ('written2','finalizing','written');
INSERT INTO `SearchDataTags` VALUES ('written2','release','written');
INSERT INTO `SearchDataTags` VALUES ('written2','upload','written');
INSERT INTO `SearchDataTags` VALUES ('written2','ship','written');
INSERT INTO `SearchDataTags` VALUES ('written3','3','written');
INSERT INTO `SearchDataTags` VALUES ('written3','workflow','written');
INSERT INTO `SearchDataTags` VALUES ('written3','process','written');
INSERT INTO `SearchDataTags` VALUES ('written4','4','written');
INSERT INTO `SearchDataTags` VALUES ('written4','sound','written');
INSERT INTO `SearchDataTags` VALUES ('written4','soundscript','written');
INSERT INTO `SearchDataTags` VALUES ('written5','5','written');
INSERT INTO `SearchDataTags` VALUES ('written5','sprites','written');
INSERT INTO `SearchDataTags` VALUES ('written5','worldspawn','written');
INSERT INTO `SearchDataTags` VALUES ('written5','detail sprites','written');
INSERT INTO `SearchDataTags` VALUES ('written6','6','written');
INSERT INTO `SearchDataTags` VALUES ('written6','hotkey','written');
INSERT INTO `SearchDataTags` VALUES ('written7','7','written');
INSERT INTO `SearchDataTags` VALUES ('written7','cloud','written');
INSERT INTO `SearchDataTags` VALUES ('written7','skybox','written');
INSERT INTO `SearchDataTags` VALUES ('written8','8','written');
INSERT INTO `SearchDataTags` VALUES ('written8','protect','written');
INSERT INTO `SearchDataTags` VALUES ('written8','decompiling','written');
INSERT INTO `SearchDataTags` VALUES ('written9','9','written');
INSERT INTO `SearchDataTags` VALUES ('written9','process','written');
INSERT INTO `SearchDataTags` VALUES ('written9','workflow','written');
INSERT INTO `SearchDataTags` VALUES ('written10','10','written');
INSERT INTO `SearchDataTags` VALUES ('written10','vide','written');
INSERT INTO `SearchDataTags` VALUES ('written10','pack','written');
INSERT INTO `SearchDataTags` VALUES ('written11','11','written');
INSERT INTO `SearchDataTags` VALUES ('written11','screenshot','written');
INSERT INTO `SearchDataTags` VALUES ('written11','image','written');
INSERT INTO `SearchDataTags` VALUES ('written12','12','written');
INSERT INTO `SearchDataTags` VALUES ('written12','propper','written');
INSERT INTO `SearchDataTags` VALUES ('written12','steampipe','written');
INSERT INTO `SearchDataTags` VALUES ('written13','13','written');
INSERT INTO `SearchDataTags` VALUES ('written13','custom','written');
INSERT INTO `SearchDataTags` VALUES ('written13','content','written');
INSERT INTO `SearchDataTags` VALUES ('written13','contamination','written');
INSERT INTO `SearchDataTags` VALUES ('written14','14','written');
INSERT INTO `SearchDataTags` VALUES ('written14','port','written');
INSERT INTO `SearchDataTags` VALUES ('written14','porting','written');
INSERT INTO `SearchDataTags` VALUES ('written14','content','written');
INSERT INTO `SearchDataTags` VALUES ('written15','15','written');
INSERT INTO `SearchDataTags` VALUES ('written15','remote','written');
INSERT INTO `SearchDataTags` VALUES ('written15','compile','written');
INSERT INTO `SearchDataTags` VALUES ('written15','compiling','written');
INSERT INTO `SearchDataTags` VALUES ('ht1','1','ht');
INSERT INTO `SearchDataTags` VALUES ('ht1','cubemap','ht');
INSERT INTO `SearchDataTags` VALUES ('ht2','2','ht');
INSERT INTO `SearchDataTags` VALUES ('ht2','vertex','ht');
INSERT INTO `SearchDataTags` VALUES ('ht2','shifting','ht');
INSERT INTO `SearchDataTags` VALUES ('ht3','3','ht');
INSERT INTO `SearchDataTags` VALUES ('ht3','displacement','ht');
INSERT INTO `SearchDataTags` VALUES ('ht3','edge','ht');
INSERT INTO `SearchDataTags` VALUES ('ht3','shadow','ht');
INSERT INTO `SearchDataTags` VALUES ('tips','tips','ht');
INSERT INTO `SearchDataTags` VALUES ('tips','tricks','ht');
INSERT INTO `SearchDataTags` VALUES ('legacy1','1','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy1','started','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy1','beginning','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy2','2','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy2','prop','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy2','prop_static','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy2','prop_dynamic','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy3','3','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy3','lighting','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy3','light','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy3','light_spot','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy4','4','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy4','door','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy4','buyzone','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy5','5','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy5','water','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy5','displacement','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy6','6','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy6','elevator','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy7','7','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy7','deathrun','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy7','input','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy7','output','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy7','io','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy8','8','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy8','train','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy8','laser','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy8','parent','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy8','parenting','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy9','9','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy9','texture','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy9','custom','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy9','normal','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy10','10','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy10','pakrat','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy10','vmex','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy11','11','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy11','turret','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy11','cutting','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy11','angle','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy12','12','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy12','point_template','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy12','template','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy12','spawn','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy13','13','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy13','keypad','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy13','password','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy14','14','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy14','textures','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy14','translucent','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy14','transparent','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy15','15','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy15','custom','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy15','content','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy16','16','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy16','trigger_teleport','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy16','teleport','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy16','hurt','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy16','trigger_hurt','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy16','heal','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy17','17','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy17','afk','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy17','point_servercommand','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy18','18','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy18','cell','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy18','shading','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy19','19','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy19','math_counter','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy19','counter','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy19','func_breakable','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy19','breakable','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy19','logic_case','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy20','20','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy20','demo','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy20','smoothing','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy21','21','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy21','optimization','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy21','hint','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy21','skip','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy21','areaportal','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy22','22','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy22','waterfall','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy23','23','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy23','stairs','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy23','arches','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy23','primitives','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy24','24','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy24','propper','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy25','25','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy25','camera','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy25','rt','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy25','_rt_camera','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy26','26','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy26','refract','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy26','textures','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy27','27','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy27','sound','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy27','ambient_generic','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy28','28','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy28','compiling','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy28','vrad','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy28','vvis','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy28','vbsp','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy29','29','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy29','ragdoll','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy29','prop_ragdoll','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy30','30','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy30','skybox','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy30','sky_camera','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy31','31','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy31','menu','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy32','32','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy32','filter','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy32','filter_activator_team','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy32','filter_activator_damage','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy32','filters','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy33','33','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy33','intput','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy33','output','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy33','io','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy34','34','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy34','hole','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy34','displacement','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy35','35','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy36','36','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy36','timer','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy36','logic_timer','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy37','37','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy37','orange','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy37','box','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy37','features','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy38','38','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy38','graphics','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy39','39','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy39','visgroup','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy40','40','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy40','displacement','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy40','sew','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy41','41','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy41','radar','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy41','overview','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy42','42','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy42','lights.rad','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy42','rad','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy43','43','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy43','water','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy43','dynamic','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy44','44','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy44','map','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy44','background','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy45','45','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy45','water','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy46','46','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy46','weather','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy46','effect','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy47','47','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy47','sprites','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy47','worldspawn','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy47','detail.vbsp','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy48','48','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy48','speed','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy48','gravity','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy49','49','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy49','portal','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy49','stairs','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy50','50','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy50','skybox','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy50','sky_camera','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy51','51','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy51','cable','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy51','rope','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy51','keyfram_rope','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy51','move_rope','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy52','52','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy52','street','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy52','light','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy53','53','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy53','cubemap','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy53','env_cubemap','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy53','reflections','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy54','54','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy54','prop','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy54','prop_static','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy54','prop_dynamic','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy55','55','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy55','hdr','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy55','light','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy55','lighting','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy56','56','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy56','sound','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy56','soundscape','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy56','env_soundscape','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy57','57','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy57','relay','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy57','logic_relay','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy57','toggle','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy57','switch','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy58','58','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy58','game_ui','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy59','59','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy59','path_track','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy59','func_tracktain','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy60','60','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy60','console','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy60','chat','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy60','point_servercommand','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy61','61','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy61','demo','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy61','smoothing','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy62','62','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy62','jailbreak','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy62','jb','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy63','63','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy63','game_end','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy63','score','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy64','64','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy64','trigger_look','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy64','look','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy65','65','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy65','magnet','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy65','phys_magnet','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy66','66','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy66','color','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy66','correction','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy67','67','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy67','roads','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy68','68','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy68','func_viscluster','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy68','viscluster','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy69','69','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy69','keycard','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy70','70','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy70','change','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy70','route','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy70','logic_auto','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy70','env_global','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy71','71','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy71','stair','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy72','72','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy72','displacement','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy72','cave','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy73','73','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy73','info_particle_system','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy73','particle','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy73','system','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy74','74','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy74','lighting','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy74','light','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy74','hdr','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy75','75','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy75','text','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy76','76','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy76','invisible','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy76','player','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy77','77','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy77','phys_ballsocket','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy77','swing','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy78','78','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy78','elevator','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy79','79','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy79','mirror','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy79','func_reflective_glass','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy80','80','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy80','env_explosion','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy80','wall','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy80','func_physbox','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy81','81','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy81','logic_measuremovement','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy81','turret','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy81','mouse','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy82','82','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy82','teleport','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy82','trigger_teleport','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy83','83','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy83','keypad','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy83','random','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy84','84','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy84','filter_activator_team','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy84','button','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy85','85','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy85','portal','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy85','parent','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy85','attachment','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy86','86','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy86','instance','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy86','func_instance','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy87','87','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy87','portal','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy87','button','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy87','indicator','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy88','88','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy88','info','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy88','signs','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy89','89','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy89','world','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy89','portals','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy89','linked_portal_door','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy90','90','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy90','portal','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy90','elevator','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy91','91','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy91','looping','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy91','soundscape','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy92','92','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy92','portals','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy92','prop_portal','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy93','93','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy93','fog','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy93','env_fog_controller','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy93','fog_volume','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy94','94','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy94','info_lighting','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy94','origin','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy95','95','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy95','env_projectedtexture','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy95','dynamic','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy95','light','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy96','96','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy96','water','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy96','river','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy96','rivers','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy97','97','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy97','game_text','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy97','point_servercommand','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy97','env_hudhint','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy98','98','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy98','break','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy98','light','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy99','99','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy99','texture','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy99','justify','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy99','alignment','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy99','align','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy100','100','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy100','particle','lg');
INSERT INTO `SearchDataTags` VALUES ('legacy100','info_particle_system','lg');
CREATE TABLE IF NOT EXISTS `SearchDataResults` (
	`name`	TEXT,
	`url`	TEXT,
	PRIMARY KEY(`name`)
);
INSERT INTO `SearchDataResults` VALUES ('v2 1','https://www.tophattwaffle.com/introducing-hammer-tutorial-v2-series-1-launching-hammer-initial-configuration-making-a-room/');
INSERT INTO `SearchDataResults` VALUES ('v2 2','https://www.tophattwaffle.com/hammer-tutorial-v2-series-2-adding-a-sky-to-your-level/');
INSERT INTO `SearchDataResults` VALUES ('v2 3','https://www.tophattwaffle.com/hammer-tutorial-v2-series-3-getting-intimate-with-brush-tool-and-introduction-to-clipping-tool/');
INSERT INTO `SearchDataResults` VALUES ('v2 4','https://www.tophattwaffle.com/hammer-tutorial-v2-series-4-leaks/');
INSERT INTO `SearchDataResults` VALUES ('v2 5','https://www.tophattwaffle.com/hammer-tutorial-v2-series-5-introduction-to-props/');
INSERT INTO `SearchDataResults` VALUES ('v2 6','https://www.tophattwaffle.com/hammer-tutorial-v2-series-6-basic-optimization/');
INSERT INTO `SearchDataResults` VALUES ('v2 7','https://www.tophattwaffle.com/hammer-tutorial-v2-series-7-vertex-tool-primitive-prefab-creation/');
INSERT INTO `SearchDataResults` VALUES ('v2 8','https://www.tophattwaffle.com/hammer-tutorial-v2-series-8-complete-lighting-tutorial/');
INSERT INTO `SearchDataResults` VALUES ('v2 9','https://www.tophattwaffle.com/hammer-tutorial-v2-series-9-displacements/');
INSERT INTO `SearchDataResults` VALUES ('v2 10','https://www.tophattwaffle.com/hammer-tutorial-v2-series-10-adding-water-to-your-level/');
INSERT INTO `SearchDataResults` VALUES ('v2 11','https://www.tophattwaffle.com/hammer-tutorial-v2-series-11-adding-doors-to-your-level/');
INSERT INTO `SearchDataResults` VALUES ('v2 12','https://www.tophattwaffle.com/hammer-tutorial-v2-series-12-input-and-output-overview/');
INSERT INTO `SearchDataResults` VALUES ('v2 13','https://www.tophattwaffle.com/hammer-tutorial-v2-series-13-creating-custom-textures-normals-vmts-packing-a-levels-content/');
INSERT INTO `SearchDataResults` VALUES ('v2 14','https://www.tophattwaffle.com/hammer-tutorial-v2-series-14-env_cubemaps-static-reflections-reflective-textures/');
INSERT INTO `SearchDataResults` VALUES ('v2 15','https://www.tophattwaffle.com/hammer-tutorial-v2-series-15-creating-a-3d-skybox/');
INSERT INTO `SearchDataResults` VALUES ('v2 16','https://www.tophattwaffle.com/hammer-tutorial-v2-series-16-adding-fog-to-your-level/');
INSERT INTO `SearchDataResults` VALUES ('v2 17','https://www.tophattwaffle.com/hammer-tutorial-v2-series-17-color-correction/');
INSERT INTO `SearchDataResults` VALUES ('v2 18','https://www.tophattwaffle.com/hammer-tutorial-v2-series-18-func_movelinear-basic/');
INSERT INTO `SearchDataResults` VALUES ('v2 19','https://www.tophattwaffle.com/hammer-tutorial-v2-series-19-parenting-attachment-points/');
INSERT INTO `SearchDataResults` VALUES ('v2 20','https://www.tophattwaffle.com/hammer-tutorial-v2-series-20-func_rotating-making-fans-and-things-spin/');
INSERT INTO `SearchDataResults` VALUES ('v2 21','https://www.tophattwaffle.com/hammer-tutorial-v2-series-21-optimization/');
INSERT INTO `SearchDataResults` VALUES ('v2 22','https://www.tophattwaffle.com/hammer-tutorial-v2-series-22-complete-sound-implementation/');
INSERT INTO `SearchDataResults` VALUES ('v2 23','https://www.tophattwaffle.com/hammer-tutorial-v2-series-23-texture-manipulation/');
INSERT INTO `SearchDataResults` VALUES ('v2 24','https://www.tophattwaffle.com/hammer-tutorial-v2-series-24-infodecal-and-info_overlays/');
INSERT INTO `SearchDataResults` VALUES ('v2 25','https://www.tophattwaffle.com/hammer-tutorial-v2-series-25-radar-overviews/');
INSERT INTO `SearchDataResults` VALUES ('v2 26','https://www.tophattwaffle.com/hammer-tutorial-v2-series-26-will-it-blend-blend-modulate/');
INSERT INTO `SearchDataResults` VALUES ('bc1','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-1-installing-and-understanding-the-sdk-tools/');
INSERT INTO `SearchDataResults` VALUES ('bc2','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-2-creating-our-first-room/');
INSERT INTO `SearchDataResults` VALUES ('bc3','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-3-shaping-brushes/');
INSERT INTO `SearchDataResults` VALUES ('bc4','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-4-intro-to-cs-level-design/');
INSERT INTO `SearchDataResults` VALUES ('bc5','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-5-building-testing-and-fixing-dev-level/');
INSERT INTO `SearchDataResults` VALUES ('bc6','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-6-introduction-to-props/');
INSERT INTO `SearchDataResults` VALUES ('bc7','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-7-introduction-to-optimization/');
INSERT INTO `SearchDataResults` VALUES ('bc8','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-8-game-modes-and-radars/');
INSERT INTO `SearchDataResults` VALUES ('bc9','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-9-texturing-your-level/');
INSERT INTO `SearchDataResults` VALUES ('bc10','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-10-displacements/');
INSERT INTO `SearchDataResults` VALUES ('bc11','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-11-lighting-part-1-basic-lighting/');
INSERT INTO `SearchDataResults` VALUES ('bc12','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-12-lighting-part-2-sprites-effects-lightmap-grid/');
INSERT INTO `SearchDataResults` VALUES ('bc13','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-13-lighting-part-3-advanced-lighting-hdr/');
INSERT INTO `SearchDataResults` VALUES ('bc14','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-14-doors-ladders-and-chickens/');
INSERT INTO `SearchDataResults` VALUES ('bc15','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-15-3d-skybox-and-fog/');
INSERT INTO `SearchDataResults` VALUES ('bc16','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-16-custom-textures-cubemaps-and-reflections/');
INSERT INTO `SearchDataResults` VALUES ('bc17','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-17-decals-and-info_overlay/');
INSERT INTO `SearchDataResults` VALUES ('bc18','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-18-sounds/');
INSERT INTO `SearchDataResults` VALUES ('bc19','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-19-optimization-part-1/');
INSERT INTO `SearchDataResults` VALUES ('bc20','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-20-optimization-part-2/');
INSERT INTO `SearchDataResults` VALUES ('bc21','https://www.tophattwaffle.com/csgo-level-design-boot-camp-day-21-finalizing-and-publishing/');
INSERT INTO `SearchDataResults` VALUES ('3ds mfp1','https://www.tophattwaffle.com/create-your-own-csgo-props-my-first-source-prop-part-1-modeling/');
INSERT INTO `SearchDataResults` VALUES ('3ds mfp2','https://www.tophattwaffle.com/create-your-own-csgo-props-my-first-source-prop-part-2-texturing/');
INSERT INTO `SearchDataResults` VALUES ('3ds mfp3','https://www.tophattwaffle.com/create-your-own-csgo-props-my-first-source-prop-part-3-exporting/');
INSERT INTO `SearchDataResults` VALUES ('3ds 1','https://www.tophattwaffle.com/3dsmax-tutorial-beginners-guide-1-introduction-to-max/');
INSERT INTO `SearchDataResults` VALUES ('3ds 2','https://www.tophattwaffle.com/3dsmax-tutorial-beginners-guide-2-creating-and-editing-geometry/');
INSERT INTO `SearchDataResults` VALUES ('3ds 3','https://www.tophattwaffle.com/3dsmax-tutorial-beginners-guide-3-creating-and-editing-splines/');
INSERT INTO `SearchDataResults` VALUES ('3ds 4','https://www.tophattwaffle.com/3dsmax-tutorial-beginners-guide-4-creating-a-simple-model-lamp/');
INSERT INTO `SearchDataResults` VALUES ('3ds 5','https://www.tophattwaffle.com/3dsmax-tutorial-beginners-guide-5-uvw-unwrap-modifier/');
INSERT INTO `SearchDataResults` VALUES ('3ds gen1','https://www.tophattwaffle.com/3dsmax-tutorial-basic-install-of-wallworm-model-tools/');
INSERT INTO `SearchDataResults` VALUES ('3ds gen2','https://www.tophattwaffle.com/3dsmax-tutorial-exporting-a-model-to-source-engine-prop_static/');
INSERT INTO `SearchDataResults` VALUES ('written1','https://www.tophattwaffle.com/lighting-tips-tricks-and-hints/');
INSERT INTO `SearchDataResults` VALUES ('written2','https://www.tophattwaffle.com/finalizing-your-level-before-release/');
INSERT INTO `SearchDataResults` VALUES ('written3','https://www.tophattwaffle.com/mapping-workflow-keeping-your-sanity-for-the-extra-long-projects/');
INSERT INTO `SearchDataResults` VALUES ('written4','https://www.tophattwaffle.com/creating-your-own-sound-scripts/');
INSERT INTO `SearchDataResults` VALUES ('written5','https://www.tophattwaffle.com/detail-props-on-world-spawn-start-to-finish/');
INSERT INTO `SearchDataResults` VALUES ('written6','https://www.tophattwaffle.com/hammer-hot-key-list/');
INSERT INTO `SearchDataResults` VALUES ('written7','https://www.tophattwaffle.com/custom-clouds-for-3d-sky-box-tutorial/');
INSERT INTO `SearchDataResults` VALUES ('written8','https://www.tophattwaffle.com/protecting-a-map-from-decompiling/');
INSERT INTO `SearchDataResults` VALUES ('written9','https://www.tophattwaffle.com/my-level-design-process/');
INSERT INTO `SearchDataResults` VALUES ('written10','https://www.tophattwaffle.com/packing-custom-content-using-vide-in-steampipe/');
INSERT INTO `SearchDataResults` VALUES ('written11','https://www.tophattwaffle.com/taking-screenshots-the-proper-way-to-showcase-your-level/');
INSERT INTO `SearchDataResults` VALUES ('written12','https://www.tophattwaffle.com/configuring-propper-for-steampipe/');
INSERT INTO `SearchDataResults` VALUES ('written13','https://www.tophattwaffle.com/custom-content-without-contamination/');
INSERT INTO `SearchDataResults` VALUES ('written14','https://www.tophattwaffle.com/porting-content-from-other-source-engine-games/');
INSERT INTO `SearchDataResults` VALUES ('written15','https://www.tophattwaffle.com/configuring-remote-compiling/');
INSERT INTO `SearchDataResults` VALUES ('ht1','https://www.tophattwaffle.com/hammer-trouble-shooting-1-css-cubemaps-wont-build/');
INSERT INTO `SearchDataResults` VALUES ('ht2','https://www.tophattwaffle.com/hammer-trouble-shooting-2-vertex-points-moving-around-on-savecompile/');
INSERT INTO `SearchDataResults` VALUES ('ht3','https://www.tophattwaffle.com/hammer-trouble-shooting-3-shadows-on-displacement-edges/');
INSERT INTO `SearchDataResults` VALUES ('tips','https://www.youtube.com/watch?v=47HR2jewQms');
INSERT INTO `SearchDataResults` VALUES ('legacy1','https://www.tophattwaffle.com/hammer-tutorial-1-simple-things-remake/');
INSERT INTO `SearchDataResults` VALUES ('legacy2','https://www.tophattwaffle.com/hammer-tutorial-2-prop-basics/');
INSERT INTO `SearchDataResults` VALUES ('legacy3','https://www.tophattwaffle.com/hammer-tutorial-3-lighting/');
INSERT INTO `SearchDataResults` VALUES ('legacy4','https://www.tophattwaffle.com/hammer-tutorial-4-de_cs_-buyzone-and-doors/');
INSERT INTO `SearchDataResults` VALUES ('legacy5','https://www.tophattwaffle.com/hammer-tutorial-5-water-displacements-and-glass-oh-my/');
INSERT INTO `SearchDataResults` VALUES ('legacy6','https://www.tophattwaffle.com/hammer-tutorial-6-elevator/');
INSERT INTO `SearchDataResults` VALUES ('legacy7','https://www.tophattwaffle.com/hammer-tutorial-7-deathrun-and-io-making/');
INSERT INTO `SearchDataResults` VALUES ('legacy8','https://www.tophattwaffle.com/hammer-tutorial-8-laser-trails-and-parented-items/');
INSERT INTO `SearchDataResults` VALUES ('legacy9','https://www.tophattwaffle.com/hammer-tutorial-9-custom-textures-and-normal-maps/');
INSERT INTO `SearchDataResults` VALUES ('legacy10','https://www.tophattwaffle.com/hammer-tutorial-10-pakrat-and-vmex/');
INSERT INTO `SearchDataResults` VALUES ('legacy11','https://www.tophattwaffle.com/hammer-tutorial-11-waffle-turret-and-cutting-to-a-angle/');
INSERT INTO `SearchDataResults` VALUES ('legacy12','https://www.tophattwaffle.com/hammer-tutorial-12-spawing-props-and-other-things/');
INSERT INTO `SearchDataResults` VALUES ('legacy13','https://www.tophattwaffle.com/hammer-tutorial-13-200-subscribers-special-keypads/');
INSERT INTO `SearchDataResults` VALUES ('legacy14','https://www.tophattwaffle.com/hammer-tutorial-14-advanced-textures-transparent-textures/');
INSERT INTO `SearchDataResults` VALUES ('legacy15','https://www.tophattwaffle.com/hammer-tutorial-15-custom-content/');
INSERT INTO `SearchDataResults` VALUES ('legacy16','https://www.tophattwaffle.com/hammer-tutorial-16-teleport-hurt-heal-and-stripping-weapons/');
INSERT INTO `SearchDataResults` VALUES ('legacy17','https://www.tophattwaffle.com/hammer-tutorial-17-making-a-afk-killer-and-firing-commands-to-a-server/');
INSERT INTO `SearchDataResults` VALUES ('legacy18','https://www.tophattwaffle.com/hammer-tutorial-18-making-cell-shading-brush-work/');
INSERT INTO `SearchDataResults` VALUES ('legacy19','https://www.tophattwaffle.com/hammer-tutorial-19-math_counter-func_breakable-and-logic_case-all-good-things-to-know/');
INSERT INTO `SearchDataResults` VALUES ('legacy20','https://www.tophattwaffle.com/hammer-tutorial-20-demo-smoothing/');
INSERT INTO `SearchDataResults` VALUES ('legacy21','https://www.tophattwaffle.com/hammer-tutorial-21-optimization/');
INSERT INTO `SearchDataResults` VALUES ('legacy22','https://www.tophattwaffle.com/hammer-tutorial-22-waterfalls/');
INSERT INTO `SearchDataResults` VALUES ('legacy23','https://www.tophattwaffle.com/hammer-tutorial-23-stairs-arches-and-more/');
INSERT INTO `SearchDataResults` VALUES ('legacy24','https://www.tophattwaffle.com/hammer-tutorial-24-propper/');
INSERT INTO `SearchDataResults` VALUES ('legacy25','https://www.tophattwaffle.com/hammer-tutorial-25-_rt_camera/');
INSERT INTO `SearchDataResults` VALUES ('legacy26','https://www.tophattwaffle.com/hammer-tutorial-26-refracting-images-advanced-textures/');
INSERT INTO `SearchDataResults` VALUES ('legacy27','https://www.tophattwaffle.com/hammer-tutorial-27-importing-custom-sounds/');
INSERT INTO `SearchDataResults` VALUES ('legacy28','https://www.tophattwaffle.com/hammer-tutorial-28-compiling/');
INSERT INTO `SearchDataResults` VALUES ('legacy29','https://www.tophattwaffle.com/hammer-tutorial-29-500th-subscriber-special-random-falling-ragdolls/');
INSERT INTO `SearchDataResults` VALUES ('legacy30','https://www.tophattwaffle.com/hammer-tutorial-30-3d-skybox/');
INSERT INTO `SearchDataResults` VALUES ('legacy31','https://www.tophattwaffle.com/hammer-tutorial-31-custom-game-menu/');
INSERT INTO `SearchDataResults` VALUES ('legacy32','https://www.tophattwaffle.com/hammer-tutorial-32-basic-filters/');
INSERT INTO `SearchDataResults` VALUES ('legacy33','https://www.tophattwaffle.com/hammer-tutorial-33-inputs-and-outputs/');
INSERT INTO `SearchDataResults` VALUES ('legacy34','https://www.tophattwaffle.com/hammer-tutorial-34-holes-in-the-walls/');
INSERT INTO `SearchDataResults` VALUES ('legacy35','https://www.tophattwaffle.com/hammer-tutorial-35-adding-counter-strike-source-to-hammer/');
INSERT INTO `SearchDataResults` VALUES ('legacy36','https://www.tophattwaffle.com/hammer-tutorial-36-timer/');
INSERT INTO `SearchDataResults` VALUES ('legacy37','https://www.tophattwaffle.com/hammer-tutorial-37-orange-box-hammer-whats-new/');
INSERT INTO `SearchDataResults` VALUES ('legacy38','https://www.tophattwaffle.com/hammer-tutorial-38-changing-the-graphics-in-hammer/');
INSERT INTO `SearchDataResults` VALUES ('legacy39','https://www.tophattwaffle.com/hammer-tutorial-39-visgrouping/');
INSERT INTO `SearchDataResults` VALUES ('legacy40','https://www.tophattwaffle.com/hammer-tutorial-40-displacements/');
INSERT INTO `SearchDataResults` VALUES ('legacy41','https://www.tophattwaffle.com/hammer-tutorial-41-custom-radar/');
INSERT INTO `SearchDataResults` VALUES ('legacy42','https://www.tophattwaffle.com/hammer-tutorial-42-glowing-textures-lights-rad/');
INSERT INTO `SearchDataResults` VALUES ('legacy43','https://www.tophattwaffle.com/hammer-tutorial-43-dynamic-water/');
INSERT INTO `SearchDataResults` VALUES ('legacy44','https://www.tophattwaffle.com/hammer-tutorial-44-making-your-own-custom-map-background/');
INSERT INTO `SearchDataResults` VALUES ('legacy45','https://www.tophattwaffle.com/hammer-tutorial-45-adding-water-the-correct-way/');
INSERT INTO `SearchDataResults` VALUES ('legacy46','https://www.tophattwaffle.com/hammer-tutorial-46-weather-effects/');
INSERT INTO `SearchDataResults` VALUES ('legacy47','https://www.tophattwaffle.com/hammer-tutorial-47-sprites-on-world-spawn-detail-vbsp/');
INSERT INTO `SearchDataResults` VALUES ('legacy48','https://www.tophattwaffle.com/hammer-tutorial-48-modifying-speed-and-gravity/');
INSERT INTO `SearchDataResults` VALUES ('legacy49','https://www.tophattwaffle.com/hammer-tutorial-49-portal-stairs/');
INSERT INTO `SearchDataResults` VALUES ('legacy50','https://www.tophattwaffle.com/hammer-tutorial-50-d-perfectly-lining-up-3d-skyboxes/');
INSERT INTO `SearchDataResults` VALUES ('legacy51','https://www.tophattwaffle.com/hammer-tutorial-51-cable-and-ropes/');
INSERT INTO `SearchDataResults` VALUES ('legacy52','https://www.tophattwaffle.com/hammer-tutorial-52-street-light-1000th-sub/');
INSERT INTO `SearchDataResults` VALUES ('legacy53','https://www.tophattwaffle.com/hammer-tutorial-53-cubemaps/');
INSERT INTO `SearchDataResults` VALUES ('legacy54','https://www.tophattwaffle.com/hammer-tutorial-54-advanced-props/');
INSERT INTO `SearchDataResults` VALUES ('legacy55','https://www.tophattwaffle.com/hammer-tutorial-55-hdr-lighting/');
INSERT INTO `SearchDataResults` VALUES ('legacy56','https://www.tophattwaffle.com/hammer-tutorial-56-soundscapes/');
INSERT INTO `SearchDataResults` VALUES ('legacy57','https://www.tophattwaffle.com/hammer-tutorial-57-multi-toggle-button/');
INSERT INTO `SearchDataResults` VALUES ('legacy58','https://www.tophattwaffle.com/hammer-tutorial-58-game_ui/');
INSERT INTO `SearchDataResults` VALUES ('legacy59','https://www.tophattwaffle.com/hammer-tutorial-59-path_track-and-func_tanktrain/');
INSERT INTO `SearchDataResults` VALUES ('legacy60','https://www.tophattwaffle.com/hammer-tutorial-60-console-chat-console-commands/');
INSERT INTO `SearchDataResults` VALUES ('legacy61','https://www.tophattwaffle.com/hammer-tutorial-61-demo-smoothing-in-css-2009-fixing-the-smooth-bug/');
INSERT INTO `SearchDataResults` VALUES ('legacy62','https://www.tophattwaffle.com/hammer-tutorial-62-jailbreak-bare-min/');
INSERT INTO `SearchDataResults` VALUES ('legacy63','https://www.tophattwaffle.com/hammer-tutorial-63-ending-a-level-adding-score/');
INSERT INTO `SearchDataResults` VALUES ('legacy64','https://www.tophattwaffle.com/hammer-tutorial-64-trigger_look/');
INSERT INTO `SearchDataResults` VALUES ('legacy65','https://www.tophattwaffle.com/hammer-tutorial-65-magnets-glock-totin-wcc/');
INSERT INTO `SearchDataResults` VALUES ('legacy66','https://www.tophattwaffle.com/hammer-tutorial-66-color-correction/');
INSERT INTO `SearchDataResults` VALUES ('legacy67','https://www.tophattwaffle.com/hammer-tutorial-67-making-roads-the-correct-way/');
INSERT INTO `SearchDataResults` VALUES ('legacy68','https://www.tophattwaffle.com/hammer-tutorial-68-func_viscluster/');
INSERT INTO `SearchDataResults` VALUES ('legacy69','https://www.tophattwaffle.com/hammer-tutorial-69-keycard-system/');
INSERT INTO `SearchDataResults` VALUES ('legacy70','https://www.tophattwaffle.com/hammer-tutorial-70-change-in-next-round-css/');
INSERT INTO `SearchDataResults` VALUES ('legacy71','https://www.tophattwaffle.com/hammer-tutorial-71-metal-stair-case/');
INSERT INTO `SearchDataResults` VALUES ('legacy72','https://www.tophattwaffle.com/hammer-tutorial-72-displacement-cave/');
INSERT INTO `SearchDataResults` VALUES ('legacy73','https://www.tophattwaffle.com/hammer-tutorial-73-info_particle_systems/');
INSERT INTO `SearchDataResults` VALUES ('legacy74','https://www.tophattwaffle.com/hammer-tutorial-74-advanced-lighting/');
INSERT INTO `SearchDataResults` VALUES ('legacy75','https://www.tophattwaffle.com/hammer-tutorial-75-css-opening-view-and-text/');
INSERT INTO `SearchDataResults` VALUES ('legacy76','https://www.tophattwaffle.com/hammer-tutorial-76-invisible-players-and-weapons/');
INSERT INTO `SearchDataResults` VALUES ('legacy77','https://www.tophattwaffle.com/hammer-tutorial-77-swinging-objects-phys_ballsocket/');
INSERT INTO `SearchDataResults` VALUES ('legacy78','https://www.tophattwaffle.com/hammer-tutorial-78-multi-floor-elevator/');
INSERT INTO `SearchDataResults` VALUES ('legacy79','https://www.tophattwaffle.com/hammer-tutorial-79-real-time-mirrors/');
INSERT INTO `SearchDataResults` VALUES ('legacy80','https://www.tophattwaffle.com/hammer-tutorial-80-blowing-up-a-wall-with-gibs/');
INSERT INTO `SearchDataResults` VALUES ('legacy81','https://www.tophattwaffle.com/hammer-tutorial-81-mouse-controlled-turret/');
INSERT INTO `SearchDataResults` VALUES ('legacy82','https://www.tophattwaffle.com/hammer-tutorial-82-random-teleport/');
INSERT INTO `SearchDataResults` VALUES ('legacy83','https://www.tophattwaffle.com/hammer-tutorial-83-random-code-key-pad/');
INSERT INTO `SearchDataResults` VALUES ('legacy84','https://www.tophattwaffle.com/hammer-tutorial-84-team-based-buttons/');
INSERT INTO `SearchDataResults` VALUES ('legacy85','https://www.tophattwaffle.com/hammer-tutorial-85-parent-attachment-points-panels-from-portal-2/');
INSERT INTO `SearchDataResults` VALUES ('legacy86','https://www.tophattwaffle.com/hammer-tutorial-86-instances-portal-2-l4d2-alien-swarm/');
INSERT INTO `SearchDataResults` VALUES ('legacy87','https://www.tophattwaffle.com/hammer-tutorial-87-portal-2-buttons-and-indicator-lights/');
INSERT INTO `SearchDataResults` VALUES ('legacy88','https://www.tophattwaffle.com/hammer-tutorial-88-portal-2-info-signs/');
INSERT INTO `SearchDataResults` VALUES ('legacy89','https://www.tophattwaffle.com/hammer-tutorial-89-portal-2-world-portals/');
INSERT INTO `SearchDataResults` VALUES ('legacy90','https://www.tophattwaffle.com/hammer-tutorial-90-portal-2-arrivaldeparture-elevators-elevator-movies-and-linking-maps/');
INSERT INTO `SearchDataResults` VALUES ('legacy91','https://www.tophattwaffle.com/hammer-tutorial-91-creating-a-soundscape-and-looping-a-wav/');
INSERT INTO `SearchDataResults` VALUES ('legacy92','https://www.tophattwaffle.com/hammer-tutorial-92-placing-portals-in-hammer/');
INSERT INTO `SearchDataResults` VALUES ('legacy93','https://www.tophattwaffle.com/hammer-tutorial-93-fog/');
INSERT INTO `SearchDataResults` VALUES ('legacy94','https://www.tophattwaffle.com/hammer-tutorial-94-info_lightinglighting-origin/');
INSERT INTO `SearchDataResults` VALUES ('legacy95','https://www.tophattwaffle.com/hammer-tutorial-95-dynamic-lighting-env_projectedtexture/');
INSERT INTO `SearchDataResults` VALUES ('legacy96','https://www.tophattwaffle.com/hammer-tutorial-96-rivers/');
INSERT INTO `SearchDataResults` VALUES ('legacy97','https://www.tophattwaffle.com/hammer-tutorial-97-in-game-messaging/');
INSERT INTO `SearchDataResults` VALUES ('legacy98','https://www.tophattwaffle.com/hammer-tutorial-98-breaking-a-light/');
INSERT INTO `SearchDataResults` VALUES ('legacy99','https://www.tophattwaffle.com/hammer-tutorial-99-texture-manipulation/');
INSERT INTO `SearchDataResults` VALUES ('legacy100','https://www.tophattwaffle.com/hammer-tutorial-100-creating-and-editing-particle-systems/');
CREATE TABLE IF NOT EXISTS `Mutes` (
	`seq_id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`snowflake`	INTEGER,
	`username`	TEXT,
	`mute_reason`	TEXT,
	`mute_duration`	INTEGER,
	`muted_by`	TEXT,
	`date`	INTEGER
);
CREATE TABLE IF NOT EXISTS `KeyVaules` (
	`key`	TEXT,
	`value`	TEXT,
	PRIMARY KEY(`key`)
);
CREATE TABLE IF NOT EXISTS `CommandUsage` (
	`seq_id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`snowflake`	INTEGER,
	`username`	TEXT,
	`command`	TEXT,
	`fullmessage`	TEXT,
	`date`	INTEGER
);
CREATE TABLE IF NOT EXISTS `ActiveMutes` (
	`snowflake`	INTEGER,
	`username`	TEXT,
	`mute_reason`	TEXT,
	`mute_duration`	INTEGER,
	`muted_by`	TEXT,
	`muted_time`	INTEGER,
	PRIMARY KEY(`snowflake`)
);
COMMIT;
